### ISSUE TITLE
Review section 3.2.3 "AWS Auto Scaling"

### ISSUE THREAD

**Issue by jburns24** [liatrio/devops-bootcamp#246]
https://devops-bootcamp.liatr.io/#/3-cloud-computing/3.2.3-auto-scaling

![Image](https://user-images.githubusercontent.com/19497855/224804073-7d3f8ba7-1ef8-4cb7-bfc3-0d8b4ba20a39.png)

Amazon is deprecating 'launch configurations' for Amazon EC2 Auto Scaling and is migrating to 'Launch Templates'. We need to update 3.2.3 to use Launch Templates 

[Migrate to Launch Templates](https://docs.aws.amazon.com/autoscaling/ec2/userguide/launch-templates.html#migrate-to-launch-templates)

```[tasklist]
### Tasks
- [x] Update the first exercise to use official spring pet clinic and centOS 9
- [x ] Update 'Launch Configuration' section to 'Launch Templates
- [x] Update Launch Configuration section to Launch Templates
```

**Comment by densellp** [comment]
Changing maven To java 7 or 8 on Amazon Linux 2 causes issues since men needs java 8 to compile the java source files, and Amazon JDK 8 is slightly different to the point where men thinks it's a JRE instead of a JDK. I might be missing something vital but I am not sure at this point. This is to build the spring pet clinic from liatrio instead of the official repo


![Image](https://user-images.githubusercontent.com/89417264/225137370-327a22f6-853f-4fb8-963d-dd678a2806de.png)

**Comment by jburns24** [comment]
https://github.com/liatrio/devops-bootcamp/issues/249
