### ISSUE TITLE
4.5.6 Jenkins replacement - SonarQube

### ISSUE THREAD

**Issue by snowmang1** [liatrio/devops-bootcamp#285]
```[tasklist]
- [x] Remove Jenkins
- [x] Write Github actions
- [x] Rewrite section with updated screenshots of SonarQube & GitHub actions
```

I have found [this](https://github.com/marketplace/actions/official-sonarqube-scan); an official plugin for GitHub actions from SonarQube that could make this replacement simple. This should use a simplistic actions as the point of this section is SonarQube,
not GitHub actions. If the plugin is used please include a link or reference so that more information is available, if desired.

**Comment by amber-beasley-liatrio** [comment]
Just making some notes...

What purpose is Jenkins serving on this page?  https://devops-bootcamp.liatr.io/#/4-software-development-practices/4.5.6-sonarqube

* "Configuring Jenkins to run the SonarQube scanner as part of a job" -- trigger SonarQube scan against code

What is the best way to use SonarQube to scan code if we want to use Github actions
  * trigger SonarQube scan on SonarQube dedicated server
  * (or) is there a SonarQube image available we could use to scan in a GitHub action

**Comment by amber-beasley-liatrio** [comment]
It's my first time using SonarQube. For the sake of time, for testing, I'm going to just run a SonarQube container instead of create a virtual host.

**Comment by jburns24** [comment]
@amber-beasley-liatrio The purpose for Jenkins in this section (as I understand it) is to be our CI/CD server where we manage our pipelines and how we integrate into our SonarQube instance for code scanning. So I believe the old pipeline would be "push to GH -> Jenkins triggers SonarQube -> Pending passing SonarQube run Jenkins Go tests -> pending passing test Jenkins builds solution". As with most sections in the bootcamp they build off of each other. So throughout the previous sections of this chapter you build a Jenkins pipeline for testing and building your Go project. 

The learning goal of this exercise is to integrate a scanner (in this case SonarQube) into our build pipeline. So how we standup SonarQube can change. I would go the path of least resistance here so campers are not fighting things outside of the learning goal. All that to say containers sounds perfect.

I have not done this exercise yet so my input might have gaps. But scanning SonarQube docs I think we will need to have our SonarQube instance communicate with github. You can use a service like [ngrok](https://ngrok.com/) to expose a local service over the web.

**Comment by baserrato** [comment]
That was the idea I was thinking that would be the simplest @jburns24 if we wanted to have the github-runners to talk to the created instance of SonarQube utilizing ngrok. 

Another way that maybe more complex and I have not fully tested this is setting up a self-hosted runner via your local machine and referencing the local version of sonarqube if we wanted to keep everything somewhat local. Ngrok still speaks to me more in terms of the exercise since it would bring a slight rabbit hole to learn about self-hosted runners.

**Comment by amber-beasley-liatrio** [comment]
Current state of the exercise is a camper standing up their own instance of Jenkins and their own instance of SonarQube.

I was thinking that we still have them stand up their own instance of SonarQube and connect to that from public GitHub (instead of standing up a Jenkins instance) to scan code on pushes?

**Comment by baserrato** [comment]
If I'm understanding right I was more thinking the complication would be in terms of an apprentice having to configure a self-hosted runner since chances are they have not done so before (wouldn't be a difficult thing but still takes time) 

Another part would be how that SonarQube action handles grabbing where SonarQube is hosted. 

If the self-hosted runner is configured to be your local machine it can reference your exposed ports in localhost. Attached a screenshot of me doing a test run to curl an application exposted in my localhost port 3000. 

<img width="666" alt="Screenshot 2023-05-17 at 12 48 23 PM" src="https://github.com/liatrio/devops-bootcamp/assets/54423854/83412a4f-7fd3-464a-bdb5-21009b56c703">

**Comment by amber-beasley-liatrio** [comment]
Would GitHub document that a self hosted runner is needed to connect to any SonarQube instance though?

https://github.com/marketplace/actions/official-sonarqube-scan

They make it seem as though if you set up SonarQube for the project and use the supplied GitHub action yaml with host and token secret defined, it should just work?

**Comment by jburns24** [comment]
@amber-beasley-liatrio -- Correct we still want them to stand up sonarqube. I think we just want to migrate the pipeline from jenkins to a GHA. Self-hosted runners will be covered specifically in another exercise so I think using a GH hosted runner is going to be easier. You should be able to use a service like ngrok to make your local instance of SonarQube reachable to public github. 

I am not confident a self hosted runner will make this smoother. And I think exposing your SonarQube instance to github proper via ngrok will be the path of least resistance.
